### PR TITLE
Update KaliDAOcrowdsale.sol

### PR DESCRIPTION
**Pull request by audsssy**
Reset `Crowdsale` struct when setting extension

### CODE REVIEW

**Comment by audsssy** [comment]
Publicizing `kaliRate` to allow public to publicly verify rate. We don't necessarily need to present it at front end but may be helpful in FAQ or other relevant sections.

**Comment by audsssy** [comment]
Additional nits: 

1. `Crowdsale` struct, specifically `purchaseTotal` and `personalPurchased`, carries data from previous crowdsales so I added logic to reset the struct in `setExtension()`
2. Added a `purchasers` mapping to `Crowdsale` struct to assist (1), resetting `personalPurchased` in preparation for new crowdsales

**Review by z0r0z — CHANGES_REQUESTED** [review]
this looks good to me @audsssy Can you set `purchaseMultiplier` to uint256? An issue we noticed with uint8 is that it can be limiting for low decimal tokens like USDC

**Comment by audsssy** [comment]
Ah yes, `purchaseMultiplier` has been now been updated to `uint256` from `uint8`.

**Comment by audsssy** [comment]
Here's an instant of updated contract - https://goerli.etherscan.io/address/0xB682e773768e68C02B8b3892CF32eA090600b4b4#code

**Pull request merged**
